/* ---------- UI COMPONENTS ---------- */
const card=(a,why)=>`<div class=cd><div class=row><div class=av style="background:hsl(${a.id*47} 55% 38%)">${ini(a.name)}</div><div><button class=lk data-a=view data-i=${a.id}>${a.name}</button>${a.vf?'<span class=vb>✔ Verified Alumnus</span>':'<span class=pd>Pending verification</span>'}<div class=mu>${a.br} · ${a.yr} batch</div></div></div><div>${a.role} at <b>${a.co}</b>, ${a.city}</div><div>${a.sk.map(s=>`<i class=tg>${s}</i>`).join('')}</div>${why?`<p class=why>${why}</p>`:''}<div class=row><button data-a=view data-i=${a.id}>View profile</button><button data-a=conn data-i=${a.id}>${S.conn.has(a.id)?'Requested ✓':'Connect'}</button><button class=p data-a=mreq data-i=${a.id} ${a.mn&&a.vf?'':'disabled'}>${a.mn?'Request Mentorship':'Not mentoring'}</button><button data-a=save data-i=${a.id} title="Save profile">${S.saved.has(a.id)?'★':'☆'}</button><button data-a=rep data-i=${a.id} title="Report">⚑</button></div></div>`;
const oc=o=>`<div class=cd><div class=row><b>${o.t}</b><span class=tg>${o.ty}</span></div><div class=mu>${o.m} · ${o.lv} · ${o.br} · posted by ${A[o.by].name}<span class=vb>✔ Verified</span></div><button class=p data-a=apply data-i=${o.id}>${S.ap.has(o.id)?'Applied ✓':'Apply or ask for referral'}</button></div>`;
const chat=r=>`${r.m.map(m=>`<div class="msg ${(m.f=='a')==(S.role=='alumni')?'me':''}">${m.t}</div>`).join('')}${r.st!='Completed'?`<div class=row><input id=m${r.id} placeholder="Write a message" style="flex:1"><button data-a=send data-i=${r.id}>Send</button></div>`:''}`;
const rc=r=>{const al=A[r.aid],v=S.role;return`<div class=cd><b>${r.type}</b> <span class=tg>${r.st}</span><div class=mu>${v=='alumni'?'From '+r.who+' to '+al.name:'With '+al.name+' at '+al.co}${r.when?' · '+r.when:''}${r.rt?' · '+'★'.repeat(r.rt):''}${v=='alumni'&&r.who==S.pf.student.name&&S.pf.student.clubs.length?' · Clubs: '+S.pf.student.clubs.join(', '):''}</div>
${r.st=='Pending'&&v=='alumni'?`<div class=row><button class=p data-a=acc data-i=${r.id}>Accept</button><button data-a=rej data-i=${r.id}>Decline</button></div>`:''}${r.st=='Accepted'?`<button data-a=sch data-i=${r.id}>Schedule session</button>`:''}${r.st=='Scheduled'&&v!='alumni'?`<button data-a=done data-i=${r.id}>Complete and give feedback ★★★★★</button>`:''}${['Accepted','Scheduled','Completed'].includes(r.st)?chat(r):''}</div>`};
const stats=()=>({stu:20+S.users.filter(u=>u.role=='student'&&u.st=='Approved').length,alu:A.length,ver:A.filter(a=>a.vf).length,mn:A.filter(a=>a.mn&&a.vf).length,rq:S.req.length,cn:S.conn.size+S.req.filter(r=>!['Pending','Declined'].includes(r.st)).length,int:O.filter(o=>o.ty=='Internship').length,job:O.filter(o=>['Job','Referral'].includes(o.ty)).length,ev:12+S.reg.size,eng:Math.min(99,58+S.act*3)});
const sc=(a,b)=>`<div><b>${a}</b><span class=mu>${b}</span></div>`;
const anl=()=>{const s=stats(),w=[41,46,52,55,58,s.eng];return`<div class=st>${sc(s.stu,'Students')}${sc(s.alu,'Alumni')}${sc(s.ver,'Verified alumni')}${sc(s.mn,'Active mentors')}${sc(s.rq,'Mentorship requests')}${sc(s.cn,'Connections')}${sc(s.int,'Internships')}${sc(s.job,'Jobs & referrals')}${sc(s.ev,'Events conducted')}${sc(s.eng+'%','Alumni engagement')}</div>
<div class=cd><b>Weekly engagement</b><div class=bars>${w.map(x=>`<i style="height:${x}%" title="${x}%"></i>`).join('')}</div><div class=mu>Last bar updates live as students and alumni act in this demo.</div></div>
<div class=cd><b>Requests by type</b>${MT.map(m=>{const n=S.req.filter(r=>r.type==m).length;return`<div class=row><span style="width:140px">${m}</span><i style="display:block;height:10px;background:var(--ac);border-radius:5px;width:${n*40+4}px"></i> ${n}</div>`}).join('')}</div>`};
