/* ---------- VIEWS ---------- */
const V={};
V.home=()=>({student:()=>`<h2>Welcome, ${S.user.name.split(' ')[0]}</h2><p class=mu>${S.user.br} · Batch of ${S.user.yr}. Tell us where you want to go and we match you with verified alumni.</p>
<div class=cd><b>What is your career goal?</b><div class=row><input id=q value="${S.q}" placeholder="I want to become a software developer." style="flex:1;min-width:200px"><button class=p data-a=find>Find alumni</button></div><div class=row>${['I want to become a software developer','I am interested in data science and ML','I want to work in product management','I want a career in embedded systems'].map(x=>`<button class=tg data-a=ex data-q="${x}">${x.slice(10)}</button>`).join('')}</div></div>
${S.q?`<h3>Recommended alumni</h3><div class=gr>${recs(4,S.q)}</div>`:''}<h3 style="margin-top:18px">New for your branch</h3>${O.filter(o=>o.br=='CSE').slice(0,2).map(oc).join('')}`,
alumni:()=>`<h2>${S.grad?'Welcome to the alumni network, '+S.user.name.split(' ')[0]:'Welcome, '+S.pf.alumni.name.split(' ')[0]}</h2>${S.grad?'<div class=cd>🎓 You graduated in 2026. Students can now find you as a mentor. This is the full loop: student, alumnus, mentor.</div>':''}
<div class=cd><b>Mentorship requests waiting</b><div class=mu>${S.req.filter(r=>r.st=='Pending').length} pending. Open Mentorship to accept or decline.</div></div>
<div class=cd><b>Post an opportunity</b><div class=row><input id=ot placeholder="Title, e.g. SDE Intern at my company" style="flex:1;min-width:200px"><select id=oty style="width:auto">${TY.map(t=>`<option>${t}</option>`).join('')}</select><button class=p data-a=post>Submit for approval</button></div></div>`,
faculty:()=>`<h2>Welcome, ${S.pf.faculty.name}</h2><p class=mu>Endorse students so alumni know who to prioritise.</p>${STU.slice(0,5).map(n=>`<div class="cd row"><b style="flex:1">${n}</b><button data-a=endorse data-n="${n}">Endorse</button></div>`).join('')}<p class=mu>Faculty mentors: ${FAC.join(', ')}</p>`,
admin:()=>{const av=A.filter(a=>!a.vf);return`<h2>College admin dashboard</h2>${anl()}<div class=cd><b>New registrations</b>${S.users.map((u,i)=>u.st=='Pending'?`<div class=row><span style="flex:1"><b>${esc(u.name)}</b> · ${u.role} · ${u.br}${u.yr?' '+u.yr:''} · ${esc(u.id)}<div class=mu>${esc(u.email)} · ${esc(u.city)}</div></span><button class=p data-a=uap data-i=${i}>Approve</button><button data-a=urj data-i=${i}>Reject</button></div>`:'').join('')||'<div class=mu>No new registrations.</div>'}</div>
<div class=cd><b>Verification queue</b>${av.map(a=>`<div class=row><span style="flex:1">${a.name}, ${a.br} ${a.yr}, ${a.co}</span><button class=p data-a=ver data-i=${a.id}>Verify alumnus</button></div>`).join('')||'<div class=mu>All alumni verified.</div>'}</div>
<div class=cd><b>Content awaiting approval</b>${S.Q.map((q,i)=>`<div class=row><span style="flex:1">${q.k=='opp'?'Opportunity: '+q.d.t:'Post: '+q.d.x}</span><button class=p data-a=appr data-i=${i}>Approve</button><button data-a=drop data-i=${i}>Reject</button></div>`).join('')||'<div class=mu>Nothing pending.</div>'}</div>
<div class=cd><b>Reports</b>${S.rep.map(r=>`<div class=row><span style="flex:1">${r.t}</span><button data-a=clr data-i=${r.id}>Resolve</button></div>`).join('')||'<div class=mu>No open reports.</div>'}</div>
<div class=cd><b>Announcement</b><div class=row><input id=an placeholder="Message to all members" style="flex:1"><button class=p data-a=ann>Send</button></div><div class=mu>Branches: CSE, IT, ECE, ME, CE · Batches 2017 to 2026</div></div>`}}[S.role])();
const alRes=()=>{const f=S.f,q=f.q.toLowerCase(),L=A.filter(a=>(!f.br||a.br==f.br)&&(!f.yr||a.yr==f.yr)&&(!f.mn||a.mn)&&(!q||[a.name,a.co,a.role,a.ind,a.city,...a.sk].join(' ').toLowerCase().includes(q)));return`<p class=mu>${L.length} alumni</p><div class=gr>${L.map(a=>card(a)).join('')}</div>`};
V.alumni=()=>`<h2>Alumni directory</h2><div class=row><input id=fq placeholder="Search company, role, industry, skill or city" value="${S.f.q}" style="flex:2;min-width:200px"><select id=fb style="flex:1"><option value="">All branches</option>${['CSE','IT','ECE','ME','CE'].map(b=>`<option ${S.f.br==b?'selected':''}>${b}</option>`).join('')}</select><select id=fy style="flex:1"><option value="">All batches</option>${[2017,2018,2019,2020,2021,2022,2023].map(y=>`<option ${S.f.yr==y?'selected':''}>${y}</option>`).join('')}</select><label><input type=checkbox id=fm ${S.f.mn?'checked':''} style="width:auto"> Open to mentoring</label></div><div id=res>${alRes()}</div>`;
V.network=()=>{const tabs=`<div class=row><button class="ch ${S.tab=='tree'?'on':''}" data-a=tab data-t=tree>Career tree</button><button class="ch ${S.tab=='map'?'on':''}" data-a=tab data-t=map>Alumni map</button></div>`;
if(S.tab=='map'){const pts=Object.entries(CT).map(([c,[x,y]])=>[c,(x-68)*14+10,(37-y)*14+10]);return`<h2>Where our alumni are</h2>${tabs}<div class=cd><svg viewBox="0 0 400 440" width="100%" role="img" aria-label="Alumni by city">${pts.map(([c,x,y])=>`<g data-a=city data-c="${c}" style="cursor:pointer"><circle cx=${x} cy=${y} r=${Math.sqrt(CN[c])*2.2} fill="var(--pr)" opacity=".55" stroke="var(--pr)"/><text x=${x+18} y=${y+4}>${c} · ${CN[c]}</text></g>`).join('')}</svg><div class=mu>City-level counts only. No addresses are stored or shown. Tap a city.</div></div>${S.city?`<h3>Alumni in ${S.city}</h3><div class=gr>${A.filter(a=>a.city==S.city).map(a=>card(a)).join('')}</div>`:''}`}
const a=A[S.sel],p=[['Your college','Where it began'],[a.br+' · '+a.yr+' batch','Branch and batch'],['Internship at '+IN[a.id%5],'Before final year'],...(FJ[a.id%6]!=a.co?[['First job at '+FJ[a.id%6],'Started career']]:[]),[a.co,'Current company'],[a.role,'Current role']];
return`<h2>Alumni career tree</h2>${tabs}<p class=mu>Pick an alumnus to explore the path they took.</p><div class=row>${A.map(x=>`<button class="ch ${x.id==S.sel?'on':''}" data-a=sel data-i=${x.id}>${x.name.split(' ')[0]} · ${x.br} ${x.yr}</button>`).join('')}</div><div class=cd>${p.map((n,i)=>`${i?'<div class=ar>↓</div>':''}<div class=nd><b>${n[0]}</b><div class=mu>${n[1]}</div></div>`).join('')}<div class=row style="justify-content:center;margin-top:12px"><button class=p data-a=mreq data-i=${a.id}>Ask ${a.name.split(' ')[0]} for mentorship</button></div></div>`};
V.mentor=()=>{const al=S.role=='alumni',my=S.req.filter(r=>al||r.who==S.user.name);
return`<h2>Mentorship</h2>${al?'':`<p class=mu>What do you need help with?</p><div class=row>${MT.map(m=>`<button class="ch ${S.mt==m?'on':''}" data-a=mt data-m="${m}">${m}</button>`).join('')}</div><h3>Suggested mentors for ${S.mt}</h3><div class=gr>${recs(3,S.q)}</div>`}<h3 style="margin-top:18px">${al?'Incoming requests':'My requests'}</h3>${my.map(rc).join('')||'<div class=mu>No requests yet. Pick a mentor above.</div>'}`};
V.opps=()=>{const c=[...TY,'Remote','Beginner','CSE'],ty=[...S.of].filter(x=>TY.includes(x)),L=O.filter(o=>(!ty.length||ty.includes(o.ty))&&(!S.of.has('Remote')||o.m=='Remote')&&(!S.of.has('Beginner')||o.lv=='Beginner')&&(!S.of.has('CSE')||['CSE','All'].includes(o.br)));
return`<h2>Opportunity hub</h2><div class=row>${c.map(x=>`<button class="ch ${S.of.has(x)?'on':''}" data-a=of data-c=${x}>${x}</button>`).join('')}</div>${L.map(oc).join('')||'<div class=mu>Nothing matches these filters. Clear a filter to see more.</div>'}`};
V.comm=()=>`<h2>Community</h2><div class=cd><textarea id=pt rows=2 placeholder="Share a project, achievement, or career advice"></textarea><button class=p data-a=share>Post for approval</button></div>${PO.map(p=>`<div class=cd><b>${p.by}</b><p style="margin:.3em 0">${p.x}</p></div>`).join('')}<h3>Upcoming events</h3>${EV.map((e,i)=>`<div class="cd row"><span style="flex:1"><b>${e[0]}</b><div class=mu>${e[1]} · Virtual</div></span><button class=${S.reg.has(i)?'':'p'} data-a=reg data-i=${i}>${S.reg.has(i)?'Registered ✓':'Register'}</button></div>`).join('')}`;
V.alerts=()=>{const h=S.nt.map(n=>`<div class=cd style="${n.r?'':'border-color:var(--ac)'}">${n.t}</div>`).join('');S.nt.forEach(n=>n.r=1);return`<h2>Notifications</h2>${h}`};
const CL=['Coding Club','Photography Club','Robotics Club','Music Society','E-Cell','Literary Club','Cultural Club','Sports Committee'],esc=s=>String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])),lnk=u=>/^https?:\/\//.test(u||'');
function collect(save){const p=S.pf[S.role],old=p.name,g=i=>$('#'+i)?$('#'+i).value.trim():null,set=(k,i)=>{const v=g(i);if(v!==null)p[k]=v};
set('name','pn');set('reg','pr');set('ach','pa');set('gh','pg');set('pw','pp');set('li','pl');set('des','pd');set('dep','pdp');set('xp','px');set('br','pbr');set('yr','py');set('exp','pe');if(!p.name)p.name=old;
if(S.role=='student'&&document.querySelector('.cl'))p.clubs=[...document.querySelectorAll('.cl:checked')].map(x=>x.value);
if(save){if(S.role=='alumni'){p.yr=+p.yr||2021;if(!S.grad){A[S.aid].br=p.br;A[S.aid].yr=p.yr}}if(S.role=='student'&&p.name!=old){S.req.forEach(r=>{if(r.who==old)r.who=p.name});S.user.name=p.name}S.edit=false;tt('Profile saved')}}
V.me=()=>{const r=S.role,p=S.pf[r],stu=r=='student',hr=stu||r=='alumni',u=S.user;
const av=`<div class=av style="width:96px;height:96px;font-size:30px;background:hsl(220 50% 38%);overflow:hidden">${p.img?`<img src="${p.img}" alt="Profile picture" style="width:100%;height:100%;object-fit:cover">`:ini(p.name)}</div>`;
const fld=(l,i,v)=>`<label class=mu style="display:block;margin:8px 0">${l}<input id=${i} value="${esc(v)}"></label>`;
if(S.edit)return`<h2>Edit profile</h2><div class=cd><div class=row>${av}<label class=mu>Profile picture (under 2 MB)<input type=file id=pic accept="image/*"></label></div>${fld('Full name','pn',p.name)}${hr?fld('Registration number','pr',p.reg):''}${r=='faculty'?fld('Designation','pd',p.des)+fld('Department','pdp',p.dep)+fld('Areas of expertise (comma separated)','px',p.xp):''}${r=='alumni'?`<label class=mu style="display:block;margin:8px 0">Branch<select id=pbr>${['CSE','IT','ECE','ME','CE'].map(b=>`<option ${p.br==b?'selected':''}>${b}</option>`).join('')}</select></label>${fld('Batch (graduation year)','py',p.yr)}<label class=mu style="display:block;margin:8px 0">Work experience, current job first. One per line: Company | Role | Years<textarea id=pe rows=4>${esc(p.exp)}</textarea></label>`:''}<label class=mu style="display:block;margin:8px 0">Achievements (one per line)<textarea id=pa rows=4>${esc(p.ach)}</textarea></label>${fld('GitHub link','pg',p.gh)}${fld('Portfolio link','pp',p.pw)}${fld('LinkedIn link','pl',p.li)}${stu?`<div class=mu style="margin-top:8px">College clubs</div><div class=row>${CL.map(c=>`<label><input type=checkbox class=cl value="${c}" ${p.clubs.includes(c)?'checked':''} style="width:auto"> ${c}</label>`).join('')}</div>`:''}<div class=row style="margin-top:12px"><button class=p data-a=psave>Save profile</button><button data-a=pcancel>Cancel</button></div></div>`;
const cx=r=='alumni'?parseEx(p.exp):[],sub=stu?u.br+' · Batch of '+u.yr:r=='alumni'?p.br+' · Batch of '+p.yr+(cx[0]?' · '+esc(cx[0][1])+' at '+esc(cx[0][0]):''):r=='faculty'?[p.des,p.dep].filter(Boolean).map(esc).join(' · ')||r:r;
return`<div class=row>${av}<div><h2 style="margin:0">${esc(p.name)}</h2><span class=vb style="margin:0">✔ Verified via college email</span><div class=mu>${sub}</div>${hr&&p.reg?`<div class=mu>Registration no. ${esc(p.reg)}</div>`:''}${stu?u.sk.map(s=>`<i class=tg>${s}</i>`).join(''):''}</div></div>
${stu&&p.clubs.length?`<div class=cd style="margin-top:12px"><b>College clubs</b><div>${p.clubs.map(c=>`<i class=tg>${esc(c)}</i>`).join('')}</div></div>`:''}
${r=='faculty'?`<div class=cd style="margin-top:12px"><b>Areas of expertise</b><div>${(p.xp||'').split(',').map(x=>x.trim()).filter(Boolean).map(x=>`<i class=tg>${esc(x)}</i>`).join('')||'<span class=mu>Add your areas of expertise.</span>'}</div></div>`:''}
<div class=cd style="margin-top:12px"><b>Links</b><div class=row>${[['GitHub',p.gh],['Portfolio',p.pw],['LinkedIn',p.li]].filter(x=>lnk(x[1])).map(x=>`<a href="${esc(x[1])}" target=_blank rel=noopener>${x[0]}</a>`).join(' · ')||'<span class=mu>Add your GitHub, portfolio and LinkedIn links.</span>'}</div></div>
${r=='alumni'?`<div class=cd><b>Work experience</b>${cx.map((l,i)=>`<div style="margin:6px 0"><b>${esc(l[1])}</b> at ${esc(l[0])} ${i?'':'<span class=vb>Current</span>'}<div class=mu>${esc(l[2]||'')}</div></div>`).join('')||'<div class=mu>Add your work experience.</div>'}</div>`:''}
<div class=cd><b>Achievements</b>${p.ach.split('\n').filter(Boolean).map(a=>`<div>🏆 ${esc(a)}</div>`).join('')||'<div class=mu>Add your achievements.</div>'}</div>
<button class=p data-a=pedit>Edit profile</button>
<div class=cd style="margin-top:12px"><b>Privacy</b><select style="margin:6px 0"><option>Visible to my college</option><option>Alumni and faculty only</option><option>Connections only</option></select><div class=mu>Phone numbers and personal emails are never shown. You can report or block anyone.</div></div>
${r=='alumni'?`<div class=cd><b>Your journey</b><div class=row><span class=tg>Student ✓</span>→<span class=tg>Intern ✓</span>→<span class=tg>Alumnus ✓</span>→<span class=tg style="background:var(--pr);color:var(--pt)">Mentor (you are here)</span></div><div class=mu>${S.grad?'You graduated in 2026 and can now mentor students, so the loop continues.':'You started as a student here. Now you help the next batch.'}</div></div>`:''}`};
V.aprof=()=>{const a=A[S.vw],ex=parseEx(a.id==S.aid&&!S.grad?S.pf.alumni.exp:(a.ex||genEx(a))),j=l=>`<div class=cd style="margin:0 0 8px"><b>${esc(l[1])}</b> at ${esc(l[0])}<div class=mu>${esc(l[2]||'')}</div></div>`;
return`<button data-a=go data-p=alumni>← Back to directory</button><div class=row style="margin-top:12px"><div class=av style="width:80px;height:80px;font-size:26px;background:hsl(${a.id*47} 55% 38%)">${ini(a.name)}</div><div><h2 style="margin:0">${a.name}</h2>${a.vf?'<span class=vb style="margin:0">✔ Verified Alumnus</span>':'<span class=pd style="margin:0">Pending verification</span>'}<div>${a.br} · Batch of ${a.yr}</div><div class=mu>${a.role} at ${a.co} · ${a.city}</div></div></div>
<div class=cd style="margin-top:12px"><b>Skills</b><div>${a.sk.map(s=>`<i class=tg>${s}</i>`).join('')}</div><div class=mu>Can help with: ${a.mn?'career guidance, resume review, mock interviews':'not mentoring right now'}</div></div>
<div class=cd><b>Work experience</b><div class=mu style="margin:4px 0">Current</div>${ex[0]?j(ex[0]):'<div class=mu>Not listed.</div>'}<div class=mu style="margin:4px 0">Previous companies</div>${ex.slice(1).map(j).join('')||'<div class=mu>No previous roles listed.</div>'}</div>
<div class=row><button data-a=conn data-i=${a.id}>${S.conn.has(a.id)?'Requested ✓':'Connect'}</button><button class=p data-a=mreq data-i=${a.id} ${a.mn&&a.vf?'':'disabled'}>Request Mentorship</button></div>`};
const NV={student:[['home','🏠','Home'],['network','🕸','Network'],['alumni','🎓','Alumni'],['mentor','🤝','Mentorship'],['opps','💼','Opportunities'],['comm','💬','Community'],['alerts','🔔','Alerts'],['me','👤','Profile']]};
NV.alumni=NV.faculty=NV.student;NV.admin=[NV.student[0],NV.student[2],NV.student[4],NV.student[5],NV.student[6]];
const SUF=['n','dob','g','m','c','e','id','b','y','d','x','co','jr','s','p','p2'];
const suGet=()=>{SUF.forEach(k=>{const e=$('#su_'+k);if(e)S.su[k]=(k=='p'||k=='p2')?e.value:e.value.trim()});const c=$('#su_ok');if(c)S.su.ok=c.checked};
const suErr=v=>{const E=[],r=v.r,y=+v.y;if(v.n.length<3)E.push('Enter your full name.');if(!v.dob)E.push('Enter your date of birth.');if(!v.g)E.push('Select your gender.');if(!/^\d{10}$/.test(v.m))E.push('Mobile number must be 10 digits.');if(!v.c)E.push('Enter your city.');
if(!new RegExp('^[^@\\s]+@'+S.college.d.replace(/\./g,'\\.')+'$','i').test(v.e))E.push('Use your college email, like name@'+S.college.d+'.');if(v.id.length<5)E.push((r=='faculty'?'Employee ID':'Registration number')+' is required (at least 5 characters).');
if(S.users.some(u=>u.id.toUpperCase()==v.id.toUpperCase())||Object.values(ACC).some(a=>a.id.toUpperCase()==v.id.toUpperCase()))E.push('This ID is already registered.');
if(!v.b)E.push(r=='faculty'?'Select your department.':'Select your branch.');
if(r=='student'&&!(y>=2026&&y<=2032))E.push('Batch year must be between 2026 and 2032.');if(r=='alumni'&&!(y>=1990&&y<=2026))E.push('Graduation year must be between 1990 and 2026.');
if(r=='alumni'&&(!v.co||!v.jr))E.push('Enter your current company and job role.');if(r=='faculty'&&!v.d)E.push('Select your designation.');
if(v.p.length<8||!/[A-Za-z]/.test(v.p)||!/\d/.test(v.p))E.push('Password needs 8 or more characters with letters and numbers.');if(v.p!=v.p2)E.push('Passwords do not match.');if(!v.ok)E.push('Please confirm that your details are correct.');return E};
const sf=(l,i,v,t,ph)=>`<label class=mu style="display:block;margin:8px 0">${l}<input id=su_${i} type=${t||'text'} value="${esc(v)}" ${ph?`placeholder="${ph}"`:''}></label>`,
sl=(l,i,o,v)=>`<label class=mu style="display:block;margin:8px 0">${l}<select id=su_${i}><option value="">Select</option>${o.map(x=>`<option ${v==x?'selected':''}>${x}</option>`).join('')}</select></label>`;
const signup=()=>{const v=S.su,r=v.r,f=r=='faculty',RL={student:'Student',alumni:'Alumnus',faculty:'Faculty'};
return`<main style="max-width:560px"><div class=row><span class=logo>AlumNexus</span><span class=sp></span><button data-a=lgo>← Sign in</button></div><h2>Create your account</h2><p class=mu>${esc(S.college.n)} · ${S.college.d} <button data-a=cchg>Change college</button></p><p class=mu>Only college members can join. An admin verifies every account before it goes live.</p>
<div class=row>${Object.keys(RL).map(k=>`<button class="ch ${r==k?'on':''}" data-a=surole data-r=${k}>${RL[k]}</button>`).join('')}</div>
${S.suE.length?`<div class=cd role=alert style="border-color:#dc2626;margin-top:12px"><b>Please fix these:</b>${S.suE.map(e=>`<div>• ${e}</div>`).join('')}</div>`:''}
<div class=cd style="margin-top:12px"><b>Personal details</b>${sf('Full name','n',v.n)}${sf('Date of birth','dob',v.dob,'date')}${sl('Gender','g',['Male','Female','Other','Prefer not to say'],v.g)}${sf('Mobile number','m',v.m,'tel')}${sf('City','c',v.c)}<div class=mu>Your phone number and date of birth are never shown to other members.</div></div>
<div class=cd><b>College details</b>${sf('College email (@'+S.college.d+')','e',v.e,'email','name@'+S.college.d)}${sf(f?'Employee ID':'Registration number','id',v.id)}${sl(f?'Department':'Branch','b',['CSE','IT','ECE','ME','CE'],v.b)}
${r=='student'?sf('Batch (expected graduation year)','y',v.y,'number'):''}${r=='alumni'?sf('Graduation year','y',v.y,'number')+sf('Current company','co',v.co)+sf('Current job role','jr',v.jr):''}${f?sl('Designation','d',['Assistant Professor','Associate Professor','Professor','Lecturer'],v.d)+sf('Areas of expertise (comma separated)','x',v.x):''}${f?'':sf('Skills (optional, comma separated)','s',v.s)}</div>
<div class=cd><b>Set a password</b>${sf('Password','p',v.p,'password')}${sf('Confirm password','p2',v.p2,'password')}<label class=row><input type=checkbox id=su_ok ${v.ok?'checked':''} style="width:auto"> I confirm these details are correct and I belong to this college.</label><button class=p data-a=sub style="width:100%;margin-top:10px">Create account</button></div></main>`};
function loadUser(role,u){const k=u?u.id:'demo';if(S.cur[role]==k)return;S.cur[role]=k;
if(!u){S.pf[role]=JSON.parse(PF0)[role];if(role=='student')S.user={...DEMOU};if(role=='alumni')S.aid=0;return}
const b={name:u.name,reg:u.id,ach:'',gh:'',pw:'',li:'',clubs:[],img:''};
if(role=='student'){S.pf.student=b;S.user={name:u.name,br:u.br,yr:u.yr,sk:u.sk}}
if(role=='alumni'){S.pf.alumni={...b,br:u.br,yr:u.yr,exp:u.co+' | '+u.jr+' | Current'};S.aid=u.aid}
if(role=='faculty')S.pf.faculty={...b,reg:'',des:u.des,dep:u.br,xp:u.xp}}
const COLS=[{d:'college.edu',n:'Demo Institute of Technology'},{d:'nit-demo.edu',n:'NIT Demo University'},{d:'iiit-demo.ac.in',n:'IIIT Demo'}];
const dom=u=>{try{let x=u.trim();if(!/^https?:\/\//i.test(x))x='https://'+x;const h=new URL(x).hostname.toLowerCase().replace(/^www\./,'');return/\.[a-z]{2,}$/.test(h)?h:''}catch(e){return''}};
const collegePage=()=>`<main style="max-width:480px"><div class=row><span class=logo>AlumNexus</span><span class=sp></span><button data-a=lback>← Home</button></div><h2>Find your college</h2><p class=mu>Enter your college website address. We use it to confirm your college before you sign in or create an account.</p>
<div class=cd><label class=mu style="display:block">College website<input id=cu value="${esc(S.cu)}" placeholder="www.college.edu" autocomplete=url inputmode=url></label>${S.cerr?`<div role=alert style="color:#dc2626;margin:8px 0">${esc(S.cerr)}</div>`:''}<button class=p data-a=cfind style="width:100%;margin-top:8px">Continue</button></div>
<div class=cd><b>Demo colleges</b><div class=mu>Tap one to fill in its website.</div><div class=row>${COLS.map(c=>`<button class=tg data-a=cfill data-d=${c.d}>${c.n}</button>`).join('')}</div></div></main>`;
const landing=()=>`<main><div class=row><span class=logo>AlumNexus</span><span class=sp></span><button data-a=lgo>Sign in</button><button class=p data-a=gsu>Create account</button></div><div class=hero><h1>Your College Network. <span class=gt>Your Career Advantage.</span></h1><p>Connect with verified alumni, find mentors, discover opportunities and build lifelong professional relationships.</p>
<div class=row><button class=p data-a=lgo>Get Started</button><button data-a=lgo data-p=alumni>Explore Alumni</button><button data-a=lgo data-p=mentor>Find a Mentor</button></div>
<div class=flow><b>Students</b>↔<b>Alumni</b>↔<b>Mentors</b>↔<b>Opportunities</b>↔<b>College</b></div></div>
<div class=gr>${[['✔ Verified members only','Every alumnus is approved by the college admin before getting a badge.'],['🎯 Smart matching','Share your career goal and get alumni matched to your branch and skills.'],['🤝 Structured mentorship','Request, schedule, chat and give feedback in one place.'],['🌍 A closed ecosystem','Students, alumni, faculty and admin stay connected from campus to career.']].map(x=>`<div class=cd><b>${x[0]}</b><div class=mu>${x[1]}</div></div>`).join('')}</div></main>`;
const loginPage=()=>{const g=S.lg,c=ACC[g.r],rl={student:'Student',alumni:'Alumnus',faculty:'Faculty',admin:'College admin'};
return`<main style="max-width:460px"><div class=row><span class=logo>AlumNexus</span><span class=sp></span><button data-a=lback>← Home</button></div><h2>Sign in</h2><p class=mu>${esc(S.college.n)} · ${S.college.d} <button data-a=cchg>Change college</button></p><p class=mu>Use the ID your college gave you. What you can access depends on your role.</p>
<div class=row>${Object.keys(rl).map(k=>`<button class="ch ${g.r==k?'on':''}" data-a=lrole data-r=${k}>${rl[k]}</button>`).join('')}</div>
<div class=cd style="margin-top:12px"><label class=mu style="display:block">${c.lb}<input id=lid autocomplete=username value="${esc(g.id)}"></label><label class=mu style="display:block;margin-top:10px">Password<input id=lpw type=${g.show?'text':'password'} autocomplete=current-password value="${esc(g.pw)}"></label><div class=row><button data-a=lsh>${g.show?'Hide':'Show'} password</button></div>${g.ok?`<div role=status style="color:var(--ok);margin:8px 0">${esc(g.ok)}</div>`:''}${g.err?`<div role=alert style="color:#dc2626;margin:8px 0">${g.err}</div>`:''}<button class=p data-a=dologin style="width:100%;margin-top:8px">Sign in as ${rl[g.r]}</button><p class=mu>New here? <button data-a=gsu>Create an account</button></p><p class=mu>Forgot your password? Ask your college admin to reset it. New members are approved by the admin.</p></div>
<div class=cd><b>Demo credentials</b><div class=mu>${c.lb}: ${c.id}<br>Password: ${c.pw}</div><button data-a=fill>Fill demo credentials</button></div></main>`};
function render(){document.body.className=S.role?'in':'out';const u=S.nt.filter(n=>!n.r).length;
$('#app').innerHTML=!S.role?(S.screen=='college'?collegePage():S.screen=='login'?loginPage():S.screen=='signup'?signup():landing()):`<div class=top><span class=logo>AlumNexus</span><span class=mu style="font-size:12px">${esc(S.college?S.college.n:'')}</span><span class=sp></span><select id=rs aria-label="Demo only: switch role" title="Demo only: switch role without signing in">${['student','alumni','faculty','admin'].map(r=>`<option value=${r} ${S.role==r?'selected':''}>${r}</option>`).join('')}</select><button data-a=theme title="Toggle theme">◐</button><button data-a=out>Exit</button></div><nav>${NV[S.role].map(n=>`<button class="${S.page==n[0]?'on':''}" data-a=go data-p=${n[0]}>${n[1]}<br>${n[2]}${n[0]=='alerts'&&u?' ('+u+')':''}</button>`).join('')}</nav><main>${(V[S.page]||V.home)()}</main>`}
